version: '3'
services:
  lyricscollector:
    build: lyricscollector/
    volumes:
      - ./lyricscollector/src/:/app
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017